# Generated by Django 3.2 on 2021-04-13 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210407_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='numero_identidad',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='telefono',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='tipo_identidad',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
    ]
